# Generated by Django 4.2.1 on 2024-01-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company_detail'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product_name',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
