# Generated by Django 4.2.1 on 2024-01-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='product_name',
            field=models.ManyToManyField(default='', to='api.product'),
        ),
    ]
